name: lint
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
permissions:
  contents: read
  packages: read
jobs:
  lint:
    runs-on: [self-hosted, laboratory]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.0"
          cache: "yarn"
      - name: Install yarn
        run: npm install -g yarn
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - run: yarn install
        shell: bash
      - name: Compile Contracts
        run: yarn run build:sol
      - name: Run Lint
        run: yarn run lint
